spring:
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1

eureka:
  in stance:
    prefer-ip-address: true
  clent:
    r egi ste r- with -eureka: true
    fet ch-registry: true


#开 启 熔 断 器
feign:
  hystrix:
    enabled: true
