data:
  message: '{cipher}a74431ebad3fe17818e3ef63263496f1ce401e964ec90cc94a9edaf60fe09e2b'

spring:
  application:
    name: test

server:
  port: 9999

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8101/eureka/
